language: c
env:
    global:
        secure: "dOLF0FAlTFwUrb+dkvfwEY1o6eCRx5VaOQdvEpq4QabxnJ+1aqcX88/gAjgspHWxbYZcRjsB+VdoLzpb/a1SRFm2FmIDELGg2vn/3bdX3cnVcgGSxk8LKygNoa7bxNpFOMYxLdzPhEEie2dww8C5BaFE7FqulL8+70eUQ9TmLsQ="

compiler: gcc

before_install:
    - sudo apt-get update -qq

install:
    - sudo apt-get install make gcc autoconf autoconf-doc libtool bison flex libselinux1-dev libapparmor-dev libdbus-1-dev libcap-dev

script:
    - git submodule update --init --recursive
    - ( cd .shipped/libnl && ./autogen.sh && ./configure && make -j2 )
    - make -j2
    - make -j2 test-build

notifications:
  email:
    on_success: change
    on_failure: always

addons:
  coverity_scan:
    project:
      name: "libcts"
      description: "Libct is a containers management library"
    notification_email: avagin@gmail.com
    build_command_prepend: true
    build_command:   make
    branch_pattern: devel
