language: c
env:
    global:
        - secure: "gw2NEqsdamlVFSRNFdr0PKsMM9N0/okfsAhoEMTItucduILoTjZs5CrEy7O+p7EgNrMC9ogddr1Zki3hbTmI9yunvbsmsjHx1Bn0Ud0rvOqWYku6zmxTvm6Mth2UajcnQkxypbY0FZuNi8u+C9mDOgOvEZAIbBQQajDXQx9Gi88="

compiler: gcc

before_install:
    - sudo apt-get update -qq

install:
    - sudo apt-get install make gcc autoconf autoconf-doc libtool bison flex libselinux1-dev libapparmor-dev libdbus-1-dev libcap-dev

script:
    - git submodule update --init --recursive
    - ( cd .shipped/libnl && ./autogen.sh && ./configure && make -j2 )
    - make -j2
    - make -j2 test-build

notifications:
  email:
    on_success: change
    on_failure: always

addons:
  coverity_scan:
    project:
      name: "avagin/libct"
      description: "Libct is a containers management library"
    notification_email: avagin@gmail.com
    build_command_prepend: true
    build_command:   make
    branch_pattern: coverity_scan
