language: c
env:
    global:
        - secure: "pEXXpva8xEhFaiVX1IRFejI6rogmZKfbPrPziYqVSNskemtCcLUu6vxcneOx3TnFkuUR/UaXPMSjJmHXAeTRptsV1BsQrknbq9eZXzJjur1q8Em4yTRSHGbbfAiBpJB72Jp+DJLkAYtkZky79Jncpn7HmsyVv/1sQuFMajiijzU="


compiler: gcc

before_install:
    - sudo apt-get update -qq

install:
    - sudo apt-get install make gcc autoconf autoconf-doc libtool bison flex libselinux1-dev libapparmor-dev libdbus-1-dev libcap-dev

script:
    - git submodule update --init --recursive
    - ( cd .shipped/libnl && ./autogen.sh && ./configure && make -j2 )
    - make -j2
    - make -j2 test-build

notifications:
  email:
    on_success: change
    on_failure: always

addons:
  coverity_scan:
    project:
      name: "avagin/libct"
      description: "Build submitted via Travis CI"
    notification_email: avagin@gmail.com
    build_command_prepend: true
    build_command:   "make -j 4"
    branch_pattern: coverity_scan
